version: '3.9'

services:
  suai_schedule_postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bh3AKrv0k45g1R4SbamW
      POSTGRES_DB: suaischedule
    restart: always
    ports:
      - "5678:5432"
    volumes:
      - .database/postgres/data:/var/lib/postgresql/data
    networks:
      - suai_schedule_Network

  suai_schedule_pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: triks0001000@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 31wDSuz1m4uCUViINqvQ
    ports:
      - 5050:80
    networks:
      - suai_schedule_Network

  suai_schedule_redisstack:
    container_name: rsuai_schedule_redisstack
    image: redis/redis-stack:latest
    restart: always
    volumes:
      - .redis_volume_data:/data
      - .redis_insight_volume_data:/db
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - suai_schedule_Network
 
volumes:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  suai_schedule_Network:  
    external: true