version: '3.9'

services:
  suai_schedule_fastapi:
    build: .
    command: 
      [
        "uvicorn", 
        "--factory", "main:create_app", 
        "--reload", 
        "--host", "0.0.0.0", 
        "--port", "8000"
      ] 
    restart: always
    volumes:
      - ..:/code
    ports:
      - "8000:8000"
    networks:
      - suai_schedule_Network

networks:
  suai_schedule_Network:  
    external: true