version: '3.9'

services:
  suai_schedule_db_postgres:
    image: "postgres:14-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: queue
    restart: always
    ports:
      - "5000:5432"
    volumes:
      - .database/postgres/data:/var/lib/postgresql/data
    networks:
      - suai_schedule_Network

  suai_schedule_pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: triks0001000@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - suai_schedule_Network

  redis_stack:
    container_name: redis-stack
    image: redis/redis-stack:latest
    restart: always
    volumes:
      - .redis_volume_data:/data
      - .redis_insight_volume_data:/db
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - suai_schedule_Network
 

volumes:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  suai_schedule_Network:  
    external: true