version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    environment:
      - TZ=Europe/Moscow
    ports:
      - 4567:8000
      - 9000:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
